
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionByUsernameService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:1000/transactions?wsdl")
public class TransactionByUsernameService
    extends Service
{

    private final static URL TRANSACTIONBYUSERNAMESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONBYUSERNAMESERVICE_EXCEPTION;
    private final static QName TRANSACTIONBYUSERNAMESERVICE_QNAME = new QName("http://service/", "TransactionByUsernameService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1000/transactions?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONBYUSERNAMESERVICE_WSDL_LOCATION = url;
        TRANSACTIONBYUSERNAMESERVICE_EXCEPTION = e;
    }

    public TransactionByUsernameService() {
        super(__getWsdlLocation(), TRANSACTIONBYUSERNAMESERVICE_QNAME);
    }

    public TransactionByUsernameService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONBYUSERNAMESERVICE_QNAME, features);
    }

    public TransactionByUsernameService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONBYUSERNAMESERVICE_QNAME);
    }

    public TransactionByUsernameService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONBYUSERNAMESERVICE_QNAME, features);
    }

    public TransactionByUsernameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionByUsernameService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransactionByUsername
     */
    @WebEndpoint(name = "TransactionByUsernamePort")
    public TransactionByUsername getTransactionByUsernamePort() {
        return super.getPort(new QName("http://service/", "TransactionByUsernamePort"), TransactionByUsername.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransactionByUsername
     */
    @WebEndpoint(name = "TransactionByUsernamePort")
    public TransactionByUsername getTransactionByUsernamePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "TransactionByUsernamePort"), TransactionByUsername.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONBYUSERNAMESERVICE_EXCEPTION!= null) {
            throw TRANSACTIONBYUSERNAMESERVICE_EXCEPTION;
        }
        return TRANSACTIONBYUSERNAMESERVICE_WSDL_LOCATION;
    }

}
