
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionByUsername", targetNamespace = "http://service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionByUsername {


    /**
     * 
     * @param arg0
     * @return
     *     returns service.FetchTransactions
     */
    @WebMethod
    @WebResult(name = "FetchTrannsactions", partName = "FetchTrannsactions")
    @Action(input = "http://service/TransactionByUsername/findAllByUsersRequest", output = "http://service/TransactionByUsername/findAllByUsersResponse")
    public FetchTransactions findAllByUsers(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
